### ISSUE TITLE
Consistent invalid auth error

### ISSUE THREAD

**Issue by circa10a** [conradludgate/spotify-oauth-proxy#1]
Trying to receive any token results in the following error:

```
❯ curl -X GET -H "Authorization: Basic <encoded circa10a:api-key>" https://spotify.conradludgate.com/api/token
{"error":"invalid auth"}
```

I don't _think_ I'm doing anything wrong. Can you verify the oauth proxy is working as expected?

**Comment by conradludgate** [comment]
It's possible it's not. I'll check on Monday when I'm back home

This project was pretty neglected, I'm in the middle of a [rewrite](https://github.com/conradludgate/oauth2-proxy) though.

**Comment by conradludgate** [comment]
I've taken this project down now (will update the readme). But please try out https://github.com/conradludgate/oauth2-proxy. I got it up to feature parity :)
